# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\micro\microblog\pages\page_ui\me_changeinfo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_changeinfo(object):
    def setupUi(self, changeinfo):
        changeinfo.setObjectName("changeinfo")
        changeinfo.setEnabled(True)
        changeinfo.resize(400, 600)
        changeinfo.setMinimumSize(QtCore.QSize(400, 600))
        changeinfo.setMaximumSize(QtCore.QSize(400, 600))
        changeinfo.setMouseTracking(False)
        changeinfo.setStyleSheet("border-color: rgb(255, 0, 0);\n"
"color: rgb(0, 0, 0);")

        self.changeinfo = changeinfo
        
        self.centralWidget = QtWidgets.QWidget(changeinfo)
        self.centralWidget.setObjectName("centralWidget")
        self.userinfo = QtWidgets.QGroupBox(self.centralWidget)
        self.userinfo.setGeometry(QtCore.QRect(10, 50, 381, 251))
        self.userinfo.setObjectName("userinfo")
        self.intro = QtWidgets.QLabel(self.userinfo)
        self.intro.setGeometry(QtCore.QRect(16, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.intro.setFont(font)
        self.intro.setAlignment(QtCore.Qt.AlignCenter)
        self.intro.setObjectName("intro")
        self.uname = QtWidgets.QLabel(self.userinfo)
        self.uname.setGeometry(QtCore.QRect(16, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uname.setFont(font)
        self.uname.setAlignment(QtCore.Qt.AlignCenter)
        self.uname.setObjectName("uname")
        self.intro_change = QtWidgets.QTextEdit(self.userinfo)
        self.intro_change.setGeometry(QtCore.QRect(110, 130, 241, 111))
        self.intro_change.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.intro_change.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.intro_change.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.intro_change.setTabChangesFocus(False)
        self.intro_change.setObjectName("intro_change")
        self.stime = QtWidgets.QLabel(self.userinfo)
        self.stime.setGeometry(QtCore.QRect(120, 80, 230, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stime.setFont(font)
        self.stime.setText("")
        self.stime.setObjectName("stime")
        self.nickname = QtWidgets.QLabel(self.userinfo)
        self.nickname.setGeometry(QtCore.QRect(120, 40, 230, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nickname.setFont(font)
        self.nickname.setText("")
        self.nickname.setObjectName("nickname")
        self.siguptime = QtWidgets.QLabel(self.userinfo)
        self.siguptime.setGeometry(QtCore.QRect(16, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.siguptime.setFont(font)
        self.siguptime.setAlignment(QtCore.Qt.AlignCenter)
        self.siguptime.setObjectName("siguptime")
        self.home_page = QtWidgets.QPushButton(self.centralWidget)
        self.home_page.setGeometry(QtCore.QRect(10, 540, 71, 41))
        self.home_page.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/white house.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_page.setIcon(icon)
        self.home_page.setIconSize(QtCore.QSize(30, 30))
        self.home_page.setFlat(True)
        self.home_page.setObjectName("home_page")
        self.home = QtWidgets.QLabel(self.centralWidget)
        self.home.setGeometry(QtCore.QRect(30, 575, 41, 20))
        self.home.setObjectName("home")
        self.message = QtWidgets.QPushButton(self.centralWidget)
        self.message.setGeometry(QtCore.QRect(88, 545, 75, 31))
        self.message.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("imgs/white information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.message.setIcon(icon1)
        self.message.setIconSize(QtCore.QSize(30, 30))
        self.message.setFlat(True)
        self.message.setObjectName("message")
        self.msg = QtWidgets.QLabel(self.centralWidget)
        self.msg.setGeometry(QtCore.QRect(110, 575, 41, 20))
        self.msg.setObjectName("msg")
        self.new_blog = QtWidgets.QPushButton(self.centralWidget)
        self.new_blog.setGeometry(QtCore.QRect(144, 545, 111, 51))
        self.new_blog.setAutoFillBackground(False)
        self.new_blog.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("imgs/plus sign.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_blog.setIcon(icon2)
        self.new_blog.setIconSize(QtCore.QSize(50, 50))
        self.new_blog.setFlat(True)
        self.new_blog.setObjectName("new_blog")
        self.search = QtWidgets.QPushButton(self.centralWidget)
        self.search.setGeometry(QtCore.QRect(240, 545, 61, 31))
        self.search.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("imgs/white search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search.setIcon(icon3)
        self.search.setIconSize(QtCore.QSize(30, 30))
        self.search.setFlat(True)
        self.search.setObjectName("search")
        self.me_ = QtWidgets.QPushButton(self.centralWidget)
        self.me_.setGeometry(QtCore.QRect(320, 545, 61, 31))
        self.me_.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("imgs/black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.me_.setIcon(icon4)
        self.me_.setIconSize(QtCore.QSize(30, 30))
        self.me_.setFlat(True)
        self.me_.setObjectName("me_")
        self.aboutme = QtWidgets.QLabel(self.centralWidget)
        self.aboutme.setGeometry(QtCore.QRect(330, 575, 41, 20))
        self.aboutme.setAlignment(QtCore.Qt.AlignCenter)
        self.aboutme.setObjectName("aboutme")
        self.search_ = QtWidgets.QLabel(self.centralWidget)
        self.search_.setGeometry(QtCore.QRect(260, 575, 41, 20))
        self.search_.setObjectName("search_")
        self.userinfo_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.userinfo_2.setGeometry(QtCore.QRect(10, 310, 381, 221))
        self.userinfo_2.setObjectName("userinfo_2")
        self.mail_t = QtWidgets.QLineEdit(self.userinfo_2)
        self.mail_t.setGeometry(QtCore.QRect(110, 175, 241, 26))
        self.mail_t.setObjectName("mail_t")
        self.phoneno_t = QtWidgets.QLineEdit(self.userinfo_2)
        self.phoneno_t.setGeometry(QtCore.QRect(110, 127, 241, 26))
        self.phoneno_t.setMaxLength(11)
        self.phoneno_t.setObjectName("phoneno_t")
        self.birthday_t = QtWidgets.QLineEdit(self.userinfo_2)
        self.birthday_t.setGeometry(QtCore.QRect(110, 79, 241, 26))
        self.birthday_t.setMaxLength(10)
        self.birthday_t.setObjectName("birthday_t")
        self.layoutWidget = QtWidgets.QWidget(self.userinfo_2)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 20, 81, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gender = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gender.setFont(font)
        self.gender.setAlignment(QtCore.Qt.AlignCenter)
        self.gender.setObjectName("gender")
        self.verticalLayout.addWidget(self.gender)
        self.birthday = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.birthday.setFont(font)
        self.birthday.setAlignment(QtCore.Qt.AlignCenter)
        self.birthday.setObjectName("birthday")
        self.verticalLayout.addWidget(self.birthday)
        self.phoneno = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.phoneno.setFont(font)
        self.phoneno.setAlignment(QtCore.Qt.AlignCenter)
        self.phoneno.setObjectName("phoneno")
        self.verticalLayout.addWidget(self.phoneno)
        self.mail = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mail.setFont(font)
        self.mail.setAlignment(QtCore.Qt.AlignCenter)
        self.mail.setObjectName("mail")
        self.verticalLayout.addWidget(self.mail)
        self.genderBox = QtWidgets.QComboBox(self.userinfo_2)
        self.genderBox.setGeometry(QtCore.QRect(110, 32, 241, 26))
        self.genderBox.setObjectName("genderBox")
        self.genderBox.addItem("")
        self.genderBox.addItem("")
        self.cancle_btn = QtWidgets.QCommandLinkButton(self.centralWidget)
        self.cancle_btn.setGeometry(QtCore.QRect(150, 10, 101, 41))
        self.cancle_btn.setObjectName("cancle_btn")
        self.confirm_btn = QtWidgets.QCommandLinkButton(self.centralWidget)
        self.confirm_btn.setGeometry(QtCore.QRect(280, 10, 101, 41))
        self.confirm_btn.setObjectName("confirm_btn")
        #changeinfo.setCentralWidget(self.centralWidget)

        self.retranslateUi(changeinfo)
        # self.home_page.clicked.connect(self.home_page.click)
        # self.message.clicked.connect(self.message.click)
        # self.new_blog.clicked.connect(self.new_blog.click)
        # self.search.clicked.connect(self.search.click)
        # self.me_.clicked.connect(self.me_.click)
        self.cancle_btn.clicked.connect(self.cancle_btn.click)
        self.confirm_btn.clicked.connect(self.confirm_btn.click)
        # QtCore.QMetaObject.connectSlotsByName(changeinfo)

    def retranslateUi(self, changeinfo):
        _translate = QtCore.QCoreApplication.translate
        changeinfo.setWindowTitle(_translate("changeinfo", "修改信息"))
        self.userinfo.setTitle(_translate("changeinfo", "账号信息"))
        self.intro.setText(_translate("changeinfo", "简    介"))
        self.uname.setText(_translate("changeinfo", "昵    称"))
        self.intro_change.setPlaceholderText(_translate("changeinfo", "输入您的个人简介"))
        self.siguptime.setText(_translate("changeinfo", "注册时间"))
        self.home.setText(_translate("changeinfo", "微 博"))
        self.msg.setText(_translate("changeinfo", "消 息"))
        self.aboutme.setText(_translate("changeinfo", "我"))
        self.search_.setText(_translate("changeinfo", "发 现"))
        self.userinfo_2.setTitle(_translate("changeinfo", "个人信息"))
        self.birthday_t.setPlaceholderText(_translate("changeinfo", "2018-08-08"))
        self.gender.setText(_translate("changeinfo", "性    别"))
        self.birthday.setText(_translate("changeinfo", "生    日"))
        self.phoneno.setText(_translate("changeinfo", "手机号码"))
        self.mail.setText(_translate("changeinfo", "邮    箱"))
        self.genderBox.setItemText(0, _translate("changeinfo", "美女"))
        self.genderBox.setItemText(1, _translate("changeinfo", "帅哥"))
        self.cancle_btn.setText(_translate("changeinfo", "取消返回"))
        self.confirm_btn.setText(_translate("changeinfo", "确认修改"))


    def get_info(self):
        self.uname.setText('翱翔的格格巫')
        info = ['F','1991-01-24','2018-05-20','既然选择了远方,便只顾风雨兼程! 乘风破浪会有时,直挂云帆济沧海!','1024','256']
        self.birthday_t.setText(info[1])
        if info[0] == 'F':
            self.gender_t.setText('女')
        else:
            self.gender_t.setText('男')
        self.stime_t.setText(info[2])
        self.intro.setText(info[3])
        self.blog_count.setText(info[4])
        self.good_count.setText(info[5])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    changeinfo = QtWidgets.QMainWindow()
    ui = Ui_changeinfo()
    ui.setupUi(changeinfo)
    changeinfo.show()
    sys.exit(app.exec_())

